# This is a basic workflow to help you get started with Actions

name: Page-Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: run deploy
        run: |
          
          git config --global core.symlinks false

      - uses: actions/checkout@v2
        name: checkout main code
        with: 
          path: main

      - uses: actions/checkout@v2
        name: checkout deployTemp
        with: 
          path: deployTemp
          ref: page
          fetch-depth: 0

      - name: run deploy
        run: |
          
          git clone ./deployTemp/.git deploy --bare
          cd deployTemp
          git config --local receive.denyCurrentBranch updateInstead
          


      - uses: actions/checkout@v2
        name: checkout tool
        with: 
          repository: nota-game/Nota.Site.Generator
          path: tool

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
        
      - name: Restore dependencies
        run: dotnet restore ./tool
      - name: Build
        run: dotnet build --no-restore ./tool

      - name: run
        run: |
          cd main
          dotnet run --no-restore --project ./../tool/Nota.Site.Generator/Nota.Site.Generator.csproj

      - name: deploy to temp
        run: |
          cd ./deploy
          ls
          git push origin page:page


      - name: deploy to page
        run: |
          cd ./deployTemp
          ls
          git reset --hard
          ls
          git push 

